= ENV Config Manager
:toc:
:sectnums:
:sectanchors:

== Intro

Yet Another Config Manager ? Yep!

In short:

- written in Typescript
- available for Typescript or Javascript
- You create your config specs using a Factory
- Yaml support will come later
- your config is then loaded from your ENV or .env file
- your config is validated according to your specs
- your config is made available to you in a super easy way


== Usage

You may have a look at the samples in the `samples` folder. There are simple demos in Typescript and Javascript.

In short, you first need to define the specs of your config. It may look like:

[source,typescript]
----
include::samples/01_ts_basic_valid/configSpecs.ts[]
----

Once you defined the specs for your config, you need to create an `.env` file (unless you plan on passing the config as Environment Variables). It looks as following for the specs mentioned above:

----
include::samples/01_ts_basic_valid/.env[]
----

You may now use your config:

[source, typescript]
----
include::samples/01_ts_basic_valid/index.ts[]
----


WARNING: You should never display your config, especially in your logs, as it may contain some secrets! Instead, use the Print() method of the ConfigManager, it will mask sensible data.

== Dev

First run:

    yarn setup

Then you may for instance:

    yarn test:watch

include::samples/README.adoc[leveloffset=+1]
