name: Check

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install tooling
        run: |
          npm install --global yarn
          yarn --version

      - name: Setup
        run: |
          yarn setup
          yarn install

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test

      - name: Building
        run: yarn build

      - name: Build pack
        run: yarn pack
